#!/bin/bash
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Update the gcam libraries from google3
#

if [ $# -ne 1 ]; then
  echo "`basename $0`: Build and update the gcam libraries from google3"
  echo ""
  echo "Usage: ./`basename $0` <google3 base path>"
  echo "For example, \"./`basename $0` ~/google3\""
  echo ""
  exit
fi

######################################################################
# Setup paths

GOOGLE3_PATH="$1"

GOOGLE3_HARDWARE="hardware"
GOOGLE3_GOOGLEX="googlex"
GOOGLE3_GCAM_PATH="hardware/gchips/paintbox/googlex/gcam/hdrplus"

GOOGLE3_GCAM_OUT="blaze-bin/${GOOGLE3_GCAM_PATH}"
GOOGLE3_GCAM_TARGET="libgcam-package"
GOOGLE3_GCAM_OUT_TGZ="libgcam.tgz"
GOOGLE3_HALIDE_RUNTIME_H="third_party/halide/HalideRuntime.h"
GOOGLE3_HALIDE_BUFFER_H="third_party/halide/HalideBuffer.h"
GOOGLE3_IMX_OUT="hardware/gchips/paintbox/prebuilts/lib/arm64-v8a/libimageprocessor.so"
GOOGLE3_IMX_H="third_party/halide/paintbox/src/runtime/imx.h"
GOOGLE3_PCG_GEN_SH="hardware/gchips/paintbox/scripts/generate_all_pbserver_pcgs.sh"

ANDROID_PREBUILT_PATH="vendor/google_paintbox/prebuilts/"
ANDROID_LIB_PATH="${ANDROID_PREBUILT_PATH%%/}/libs"
ANDROID_INC_PATH="${ANDROID_LIB_PATH%%/}/include"
ANDROID_PCG_PATH="${ANDROID_PREBUILT_PATH%%/}/compiled_graph"

GOOGLE3_GCAM_FULL_PATH="${GOOGLE3_PATH%%/}/${GOOGLE3_GCAM_PATH}"
GOOGLE3_GCAM_TARGET_FULL_PATH="${GOOGLE3_GCAM_PATH%%/}:${GOOGLE3_GCAM_TARGET}"
GOOGLE3_GCAM_OUT_FULL_PATH="${GOOGLE3_PATH%%/}/${GOOGLE3_GCAM_OUT}"
GOOGLE3_GCAM_OUT_TGZ_FULL="${GOOGLE3_GCAM_OUT_FULL_PATH%%/}/${GOOGLE3_GCAM_OUT_TGZ}"
GOOGLE3_HALIDE_RUNTIME_H_FULL_PATH="${GOOGLE3_PATH%%/}/blaze-genfiles/third_party/halide/halide_runtime_headers/${GOOGLE3_HALIDE_RUNTIME_H}"
GOOGLE3_HALIDE_BUFFER_H_FULL_PATH="${GOOGLE3_PATH%%/}/blaze-genfiles/third_party/halide/halide_runtime_headers/${GOOGLE3_HALIDE_BUFFER_H}"
GOOGLE3_IMX_OUT_FULL_PATH="${GOOGLE3_PATH%%/}/${GOOGLE3_IMX_OUT}"
GOOGLE3_IMX_H_FULL_PATH="${GOOGLE3_PATH%%/}/${GOOGLE3_IMX_H}"

ANDROID_PREBUILT_FULL_PATH="${ANDROID_BUILD_TOP%%/}/${ANDROID_PREBUILT_PATH}"
ANDROID_LIB_FULL_PATH="${ANDROID_BUILD_TOP%%/}/${ANDROID_LIB_PATH}"
ANDROID_INC_FULL_PATH="${ANDROID_BUILD_TOP%%/}/${ANDROID_INC_PATH}"
ANDROID_GCAM_LIB_FULL_PATH="${ANDROID_LIB_FULL_PATH%%/}/libgcam.so"
ANDROID_HALIDE_RUNTIME_H="${ANDROID_INC_FULL_PATH%%/}/${GOOGLE3_HALIDE_RUNTIME_H}"
ANDROID_HALIDE_BUFFER_H="${ANDROID_INC_FULL_PATH%%/}/${GOOGLE3_HALIDE_BUFFER_H}"
ANDROID_IMX_OUT_FULL_PATH="${ANDROID_LIB_FULL_PATH%%/}/libimageprocessor.so"
ANDROID_IMX_H_FULL_PATH="${ANDROID_INC_FULL_PATH%%/}/imx.h"

ANDROID_PCG_FULL_PATH="${ANDROID_BUILD_TOP%%/}/${ANDROID_PCG_PATH}"
TMP_PCG_FULL_PATH="/tmp/pcg"

######################################################################
# Verify paths

# Verify environment
if prodcertstatus -q; then true
else
  echo "No valid prodaccess cert!"
  return 1
fi
if [ -z "${ANDROID_BUILD_TOP}" ]; then
  echo "No Android path found. Run envsetup"
  return 1
fi

# Verify gcam paths
if [ ! -d "${GOOGLE3_GCAM_FULL_PATH}" ]; then
  echo "${GOOGLE3_GCAM_FULL_PATH} does not exist!"
  return 1
fi
if [ ! -r "${GOOGLE3_GCAM_FULL_PATH}/BUILD" ]; then
  echo "${GOOGLE3_GCAM_FULL_PATH} does not contain a readable BUILD file. Wrong path?"
  return 1
fi
if grep -q gcam "${GOOGLE3_GCAM_FULL_PATH}/BUILD"; then true
else
  echo "${GOOGLE3_GCAM_FULL_PATH}/BUILD does not mention gcam. Wrong path?"
  return 1
fi

######################################################################
# Build libgcam target on google3

echo -e "\e[1;34m** Building libgcam library\e[00m"

pushd ${GOOGLE3_PATH}

# Generate PCG
rm -rf ${TMP_PCG_FULL_PATH}
${GOOGLE3_PCG_GEN_SH} --pcg_output_dir=${TMP_PCG_FULL_PATH}

# Build libgcam
blaze build \
  --define easel=1 \
  --define ipuonly=1 \
  --config=android_arm64 \
  -c opt ${GOOGLE3_GCAM_TARGET_FULL_PATH}
if [ $? -ne 0 ]; then
  echo "** Blaze opt build failure, cancelling update **"
  popd
  return 1
fi
if [ ! -r "${GOOGLE3_GCAM_OUT_TGZ_FULL}" ]; then
  echo "Can't find ${GOOGLE3_GCAM_OUT_TGZ_FULL} after build!"
  popd
  return 1
fi

pwd
pwd
pwd
ls -l ${GOOGLE3_GCAM_OUT_TGZ_FULL}


# Stash the library and headers into tmp before we clean the build
gcam_tmp_lib="$(mktemp -d)"

cp "${GOOGLE3_GCAM_OUT_TGZ_FULL}" "${gcam_tmp_lib}/"

pushd ${gcam_tmp_lib}
tar xvzf ${GOOGLE3_GCAM_OUT_TGZ}
popd

popd

# Unzip and Copy build results and place in Android tree
echo -e "\e[1;34m** Copying build results to Android tree\e[00m"

rm -rf "${ANDROID_INC_FULL_PATH}/googlex/"
rm -rf "${ANDROID_INC_FULL_PATH}/hardware/"
rm -rf "${ANDROID_INC_FULL_PATH}/third_party/"
mkdir -p "${ANDROID_INC_FULL_PATH}"

mv -vf "${gcam_tmp_lib}/libgcam.so" "${ANDROID_GCAM_LIB_FULL_PATH}"
mv -vf "${gcam_tmp_lib}/${GOOGLE3_HARDWARE}" "${ANDROID_INC_FULL_PATH}/"
mv -vf "${gcam_tmp_lib}/${GOOGLE3_GOOGLEX}" "${ANDROID_INC_FULL_PATH}/"

[[ -f "$gcam_tmp_lib" ]] && rm -f "$gcam_tmp_lib"

# Copy Halide headers.
mkdir -p `dirname ${ANDROID_HALIDE_RUNTIME_H}`
cp ${GOOGLE3_HALIDE_RUNTIME_H_FULL_PATH} ${ANDROID_HALIDE_RUNTIME_H}
mkdir -p `dirname ${ANDROID_HALIDE_BUFFER_H}`
cp ${GOOGLE3_HALIDE_BUFFER_H_FULL_PATH} ${ANDROID_HALIDE_BUFFER_H}

# Copy Imx lib
cp ${GOOGLE3_IMX_OUT_FULL_PATH} ${ANDROID_IMX_OUT_FULL_PATH}
cp ${GOOGLE3_IMX_H_FULL_PATH} ${ANDROID_IMX_H_FULL_PATH}

# Copy PCG
mkdir -p ${ANDROID_PCG_FULL_PATH}
rm -rf ${ANDROID_PCG_FULL_PATH}/vhash*
cp -rf ${TMP_PCG_FULL_PATH}/* ${ANDROID_PCG_FULL_PATH}/

######################################################################
# All done.
